Refactor date parsing in Refman and EndNotes formats
rayyansys/rayyan-formats-plugins pull request #35
Opened 2022-06-27 22:22 UTC by kohrVid

GitHub Issue: https://github.com/rayyansys/rayyan-formats-plugins/issues/10

This PR refactors the way in which dates are parsed in the Refman and EndNote plugins. In particular it:
* imports the correct date when it is split between the `DA` and `PY` tags in Refman files
* imports the correct date when both the `%8` and `%D` tags are populated in EndNote files
* parses the `%7` tag used for Edition dates when this is included in the EndNote files

## Questions

* For convenience, the order of preference for the date tags in the Refman format has been changed slightly so now the `DA` tag is checked before the `Y1`/`Y2`/`Y3` tags. Changing the order makes it possible to assign the `date_line` variable in a single one-liner without as opposed to three separate lines and removes the need for reassignment. Is there a particular reason as to why the `Y` tags were originally checked first or are the changes that I've made to that part of the code ok?

2022-06-28 17:55 UTC, hammady commented on lib/rayyan-formats-plugins/plugins/endnote.rb
> +          date_array(date_line)
only `if date_line`

2022-06-28 17:55 UTC, hammady commented on lib/rayyan-formats-plugins/plugins/endnote.rb
> +        def date_array(date_line)
Can you please explain what the logic here is? I am finding trouble reasoning it.
For example, if the length is less than or equal 4, why does this denote the year? It could be "June", "12/1", "12" or anything.
In the second case, you are replacing all special characters with `-`? Then why finally split on those 3 characters if you know the separator is space?
What if the `Date.parse` fails?

2022-06-28 17:55 UTC, hammady commented on lib/rayyan-formats-plugins/plugins/endnote.rb
> +          target.edition_date_array = get_edition_date_array article
This new field is not consumed in current clients of this gem. I suggest using this line as a fallback for `date_array` if it is blank.

2022-06-28 17:55 UTC, hammady commented on lib/rayyan-formats-plugins/plugins/endnote.rb
> +          date_line = article['8'] && article['D'] ? "#{article['8']} #{article['D']}" : article['8'] || article['D']
`example2.enw` and `example3.enw` both have `%8` and `%D`, how would that work here? We cannot always combine them as they may be conflicting too.

2022-06-28 19:37 UTC, kohrVid commented on lib/rayyan-formats-plugins/plugins/endnote.rb
> +        def date_array(date_line)
Those are all points that I wish I'd considered when I raised this PR. To be honest, I think I was having trouble figuring out what to return if `Date.parse` failed and so tried to write code that would prevent it reaching that point. `Date.parse` was considered as a straight-forward way to convert dates written as words (and possibly other unexpected formats) into something that could be split so I didn't think it mattered too much which character was used as a separator.

I wonder if a method like the following might work better?:

        def date_array(date_line)
          if date_line
            if !date_line.match(/[A-Za-z]/).nil?
              return Date.parse(date_line).strftime("%Y %-m %-d").split(/[\/\s-]/)[0..2]
            end

            Date.parse(date_line).strftime("%Y %-m %-d").split(/[\/\s-]/)[0..2] rescue date_line.split(/\D+/)
          end
        end

This could return unexpected results if the year is input as two digits or if the date is written in the European format but without the year ("DD/MM" instead of "MM/DD"). I'm not sure if we'd want to take that into account as well?

2022-06-28 20:11 UTC, kohrVid commented on lib/rayyan-formats-plugins/plugins/endnote.rb
> +          date_line = article['8'] && article['D'] ? "#{article['8']} #{article['D']}" : article['8'] || article['D']
When you say "conflicting", do you mean that there's a chance that the dates could be completely different in both (e.g., two different years for the same record)? My code assumes `%D` is always a year and so relied on `Date.parse()` to handle the instances where `%8` also contains a year. However, I'm not sure what we should do if the years are different.
This also doesn't take into account different formats for `%8` so perhaps I should parse that before combining the two values? Most likely the one-liner will have to go

2022-06-28 22:37 UTC, hammady commented on lib/rayyan-formats-plugins/plugins/endnote.rb
> +          date_line = article['8'] && article['D'] ? "#{article['8']} #{article['D']}" : article['8'] || article['D']
I think the real user inputs I shared earlier might help you answer those questions.

2022-06-29 21:06 UTC, hammady commented
The second link in the EndNote `description` field is invalid. Can you please replace it with a better one?

2022-07-06 16:56 UTC, hammady commented on lib/rayyan-formats-plugins/plugins/endnote.rb
> +        def date_array(date_line)
The logic is becoming hard to follow. I suggest that you document all the cases you are covering in the PR description as checkboxes [ ] and [x]. Once you are done with implementing all, let me know and we can merge.

2022-07-10 20:53 UTC, kohrVid commented on lib/rayyan-formats-plugins/plugins/endnote.rb
> +        def date_array(date_line)
Have updated the PR description with a summary of the different date types that the plugins handle

2022-07-13 20:40 UTC, hammady commented on lib/rayyan-formats-plugins/plugins/endnote.rb
> +        def date_array(date_line)
Sounds good, what is this item `---`? If the code assumes no date in this case, then we should mark it as done with a comment. Let me know when you have fixed the unmarked ones.

2022-07-16 00:10 UTC, kohrVid commented on spec/plugins/endnote_spec.rb
> +          expect(target.date_array).to eq(["2010", "6", "1"])
I've added some comments to the file in the latest commit. Hopefully that's ok

2022-07-18 20:02 UTC, hammady commented on spec/plugins/endnote_spec.rb
> +          # Date value(s): %D Dec; %8 Dec-12-15
Is this 12 Dec, 2015?

2022-07-18 20:26 UTC, kohrVid commented on spec/plugins/endnote_spec.rb
> +          # Date value(s): %D Dec; %8 Dec-12-15
> Is this 12 Dec, 2015?

I thought that particular string indicated a range of dates (as in "from the 12th December to the 15th December") but I suppose the "15" could be the year as well. I don't really know what we should expect in this case but if it's ambiguous, I wonder if it's safer to just treat it as invalid? Would users normally expect the last two digits in a date like this to refer to the year?

2022-07-19 20:30 UTC, hammady commented on spec/plugins/endnote_spec.rb
> +          # Date value(s): %D Dec; %8 Dec-12-15
@kohrVid

2022-07-19 23:20 UTC, kohrVid commented on spec/plugins/endnote_spec.rb
> +          # Date value(s): %D Dec; %8 Dec-12-15
I've updated the PR so now "Dec-12-15" is treated as "12th December 2015". It wasn't a particularly difficult change but I do worry that it could increase the number of incorrect years recorded. The `.date_array` methods depend on `Date.parse` which will assume the current year when it's missing in a string. I think it's harder to spot when this has happened with a two-digit year than a four-digit one. Is that an acceptable amount of risk in this case?

2022-07-20 17:41 UTC, hammady requested changes

2022-07-20 17:41 UTC, hammady commented on spec/plugins/endnote_spec.rb
> +          # Date value(s): %D Dec; %8 Dec-12-15
Let's not take the risk.

2022-07-20 22:38 UTC, kohrVid commented on spec/plugins/endnote_spec.rb
> +          # Date value(s): %D Dec; %8 Dec-12-15
Cool. I've just pushed a commit to revert those changes

2022-07-20 23:03 UTC, hammady approved these changes

2022-07-20 23:04 UTC, merged