Improve file detection in MEDLINE, EndNote and CIW
rayyansys/rayyan-formats-plugins pull request #47
Opened 2022-08-12 07:03 UTC by kohrVid

Closes #45 
GH: https://github.com/rayyansys/rayyan-formats-plugins/issues/45

This PR refactors the file detection used in the MEDLINE, EndNote and CIW plugins to ensure that CSV files that begin with their respective type keys aren't incorrectly identified as MEDLINE, EndNote or CIW files.

2022-08-12 15:48 UTC, hammady requested changes

2022-08-12 15:48 UTC, hammady commented on lib/rayyan-formats-plugins/plugins/medline.rb
> +        first_line.start_with?('PMID- ')
This format allows 0 to 3 spaces before the dash, check [here](https://github.com/rayyansys/ref_parsers/blob/master/lib/ref_parsers/pubmed_parser.rb#L7).

2022-08-12 15:48 UTC, hammady commented on lib/rayyan-formats-plugins/plugins/ciw.rb
> +        first_line.start_with?('FN ')
Seems that this also may [start](https://github.com/rayyansys/ref_parsers/blob/master/lib/ref_parsers/ciw_parser.rb#L6) with `VR`.

2022-08-15 10:46 UTC, kohrVid commented on lib/rayyan-formats-plugins/plugins/medline.rb
> +        first_line.start_with?('PMID- ')
Have updated this line to use a regex instead of `start_with?` which should take the spaces into account

2022-08-15 10:46 UTC, kohrVid commented on lib/rayyan-formats-plugins/plugins/ciw.rb
> +        first_line.start_with?('FN ')
This PR should now support files that start with "FN"

2022-08-15 17:36 UTC, hammady commented on lib/rayyan-formats-plugins/plugins/ciw.rb
> +        first_line.start_with?('FN ')
You probably meant "VR".

2022-08-15 17:36 UTC, hammady approved these changes

2022-08-19 15:08 UTC, merged