Import DOI in the MEDLINE plugin
rayyansys/rayyan-formats-plugins pull request #48
Opened 2022-08-12 08:16 UTC by kohrVid

Closes #44 

At present, the MEDLINE plugin imports DOIs as part of the AID field. Going forwards, we would like to import this field separately, not unlike how this value is imported in other supported formats. If an incorrectly formatted DOI is used, the new field should return nil.

## Questions

As the way that I've implemented the `DOI` field is derived from the `.get_article_ids` method, does it make sense to change the way that the DOI is exported at the moment? If the export should be modified as well, is the `AID` field the only one that we would need to check during an the import? I've noticed that the `LID` field can sometimes contain a DOI - should the import check this field as well?

2022-08-12 16:15 UTC, hammady requested changes
Answering your questions, yes DOI should be exported as a mirror of the import procedure (i.e. from the `target.doi` too). This is a core feature because it is a common scenario to import from format 1, export to format 2, import from format 2, then export to format 3, ... If we ignore doi present in `target.doi` then we are potentially dropping dois.
For the second question, I don't know what LID is, but if you think it contains doi, then why not, please link to the docs too.

2022-08-15 11:14 UTC, kohrVid commented
> Answering your questions, yes DOI should be exported as a mirror of the import procedure (i.e. from the `target.doi` too). This is a core feature because it is a common scenario to import from format 1, export to format 2, import from format 2, then export to format 3, ... If we ignore doi present in `target.doi` then we are potentially dropping dois.
For the second question, I don't know what LID is, but if you think it contains doi, then why not, please link to the docs too.

I'm still a little unclear about exports then. From what I understand there is no top-level `DOI` field in MEDLINE documents so I could update the export so that the imported `doi` field is used to populate the DOI object in the `AID` field. 
The MEDLINE documentation states that the `LID` can contain a DOI or PII (https://www.nlm.nih.gov/bsd/mms/medlineelements.html#lid) but I'm not sure if this differs from the DOI in the `AID` field. If they are distinct, perhaps we could import that field as well but then I think we would have to decide on which type of DOI is used to populate the `doi` field (or if it could be either, which one to prioritise in imports). If the values are always the same, the imported `doi` from my first commit could be used to populate the DOI in both of the exported `AID` and `LID` fields

2022-08-15 17:41 UTC, hammady commented
> > Answering your questions, yes DOI should be exported as a mirror of the import procedure (i.e. from the `target.doi` too). This is a core feature because it is a common scenario to import from format 1, export to format 2, import from format 2, then export to format 3, ... If we ignore doi present in `target.doi` then we are potentially dropping dois.
> > For the second question, I don't know what LID is, but if you think it contains doi, then why not, please link to the docs too.
> 
> I'm still a little unclear about exports then. From what I understand there is no top-level `DOI` field in MEDLINE documents so I could update the export so that the imported `doi` field is used to populate the DOI object in the `AID` field.

Yes, that's correct.

> The MEDLINE documentation states that the `LID` can contain a DOI or PII (https://www.nlm.nih.gov/bsd/mms/medlineelements.html#lid) but I'm not sure if this differs from the DOI in the `AID` field. If they are distinct, perhaps we could import that field as well but then I think we would have to decide on which type of DOI is used to populate the `doi` field (or if it could be either, which one to prioritise in imports). If the values are always the same, the imported `doi` from my first commit could be used to populate the DOI in both of the exported `AID` and `LID` fields

I suggest that you do some research and export some results from PubMed to understand how both fields are different. I do not have an answer myself.

2022-08-16 14:36 UTC, kohrVid commented
> I suggest that you do some research and export some results from PubMed to understand how both fields are different. I do not have an answer myself.

I've had a look at a handful of MEDLINE files and they all contained LIDs with a DOI that was identical to the one in the `AID` field. The official field documentation for `AID` and [this release note for the `LID` field](https://www.nlm.nih.gov/pubs/techbull/ja08/ja08_doi.html) would suggest that the values are always the same but that the fields serve different purposes (the AID is used primarily to create links for the [LinkOut program](https://www.ncbi.nlm.nih.gov/projects/linkout/) and LIDs are used to display identifiers after citation source information).
I'm inclined to believe that we should probably import and export both of these fields, especially if users are aware of  them and expect them to perform different functions. That being said, if none of our users expect this behaviour, perhaps adding the `LID` field is unnecessary?

2022-08-16 14:40 UTC, kohrVid commented on lib/rayyan-formats-plugins/plugins/medline.rb
> +          doi[:value]&.gsub(/\s*\[doi\]$/, "")[/.+/] if !doi.nil?
@hammady, does it make sense to drop the `[doi]` tag in imports and then re-add it in exports as I've done in this PR? That seemed to be more in keeping with how the other formats handle the DOI but it does mean that in the MEDLINE format, the DOI is the only article ID type that doesn't contain a tag once it's the imported. Is that ok or is that perhaps a little inconsistent?

2022-08-16 20:02 UTC, hammady commented on lib/rayyan-formats-plugins/plugins/medline.rb
> +          emit_line('AID', "#{doi} [doi]") unless doi.nil?
What about DOIs found in `article_ids`? We need to consider both and emit DOIs without duplciates.

2022-08-18 04:14 UTC, kohrVid commented on lib/rayyan-formats-plugins/plugins/medline.rb
> +          aid_obj_to_emit = article_ids.reject { |aid_obj| aid_obj[:idtype] == :doi }
Thanks for spotting that. I've removed that line now

2022-08-18 04:15 UTC, kohrVid commented on lib/rayyan-formats-plugins/plugins/medline.rb
> +          emit_line('AID', "#{doi} [doi]") unless doi.nil?
At first I wasn't sure what you meant as the `target.doi` is currently only derived from the article IDs. I suppose you probably want to take into account a second DOI if we import LIDs. I sort of think it's clearer to have a separate field for LID imports but agree that the emit method could do with some work in the meantime. I've added a `key` argument to it so that we can use it for different types of DOIs going forwards. Hopefully that's a little better now

2022-08-18 16:50 UTC, hammady commented
> I've had a look at a handful of MEDLINE files and they all contained LIDs with a DOI that was identical to the one in the `AID` field. The official field documentation for `AID` and [this release note for the `LID` field](https://www.nlm.nih.gov/pubs/techbull/ja08/ja08_doi.html) would suggest that the values are always the same but that the fields serve different purposes (the AID is used primarily to create links for the [LinkOut program](https://www.ncbi.nlm.nih.gov/projects/linkout/) and LIDs are used to display identifiers after citation source information). I'm inclined to believe that we should probably import and export both of these fields, especially if users are aware of them and expect them to perform different functions. That being said, if none of our users expect this behaviour, perhaps adding the `LID` field is unnecessary?

The above link mentions that the `LID` is for MEDLINE what `ELocationID` is for PubMed XML. This suggests that we handle it similar to what we did in [this PR](https://github.com/rayyansys/rayyan-scrapers/pull/12/files).

2022-08-18 17:04 UTC, hammady commented on lib/rayyan-formats-plugins/plugins/medline.rb
> +          doi[:value]&.gsub(/\s*\[doi\]$/, "")[/.+/] if !doi.nil?
Yes, it makes sense because `target.doi` should contain just the DOI number and applications have this expectation, regardless of what format produced it.
I could not understand the sentence "the DOI is the only article ID type that doesn't contain a tag once it's the imported". You did not touch the `get_article_ids` in this PR, so why would you think we remove the tag from there?

2022-08-18 17:08 UTC, hammady commented on lib/rayyan-formats-plugins/plugins/medline.rb
> +          emit_line('AID', "#{doi} [doi]") unless doi.nil?
No, I didn't mean the LIDs. Again, the `target.doi` could come from a different format because this is an export. It could be the same one found in `article_ids` if the import format were MEDLINE, or there could different `article_ids` or no `article_ids` at all depending on the import format.

2022-08-19 11:04 UTC, kohrVid commented on lib/rayyan-formats-plugins/plugins/medline.rb
> +          doi[:value]&.gsub(/\s*\[doi\]$/, "")[/.+/] if !doi.nil?
I think I mixed up the changes made in the import with changes to the export. We're essentially importing the DOI twice (once in `target.doi` and again in `target.article_ids` - my  latest commit will import this value a third time via `target.location_ids`) so I guess this won't be a problem

2022-08-19 11:11 UTC, kohrVid commented on lib/rayyan-formats-plugins/plugins/medline.rb
> +          emit_line('AID', "#{doi} [doi]") unless doi.nil?
Ok. I _think_ I understand this a little better now. In this scenario, we would still need to decide on what type of DOI to export by default (i.e., if this were exported after a conversion from a format that doesn't contain AIDs or LIDs). So If we follow what was done in the  scrapers repo, does it make sense to default to returning an `AID` field and to only return an `LID` field if `target.article_ids` is nil and `target.location_ids` is present? If so, I've tried to do this in the last two commits of this PR

2022-08-19 17:39 UTC, hammady requested changes

2022-08-19 17:39 UTC, hammady commented on lib/rayyan-formats-plugins/plugins/medline.rb
> +          doi = article_ids&.detect { |lid| lid[:idtype] == :doi }
Minor syntactic issue:
```suggestion
          doi = article_ids&.detect { |aid| aid[:idtype] == :doi }
```

2022-08-19 17:39 UTC, hammady approved these changes

2022-08-19 17:41 UTC, merged